---

- name: Install iptables
  package:
    name: iptables
    state: present

- name: Install package to persist iptables rules
  package:
    name: "{{ iptables_save_package }}"
    state: present

- name: Make iptables persistance service start at boot
  service:
    name: "{{ iptables_save_service }}"
    enabled: true

- name: Initialize iptables ban chain
  iptables_raw:
    name: create-ban-chain
    weight: 0
    rules: |
      -N {{ ban_chain }}
  when: iptables_ban_hosts | bool
  notify: Persist rules

- name: Set ban chain to log chain if host banning is disabled
  set_fact:
    ban_chain: "{{ log_chain_input_drop }}"
  when: not iptables_ban_hosts