---

- name: Install iptables
  package:
    name: iptables
    state: present

- name: Install package to persist iptables rules
  package:
    name: "{{ iptables_save_package }}"
    state: present

- name: Make iptables persistance service start at boot
  service:
    name: "{{ iptables_save_service }}"
    enabled: true

- name: Firewall rule - create ban chain
  iptables_raw:
    name: create-ban-chain
    state: "{{ (iptables_ban_hosts | bool) | ternary('present', 'absent') }}"
    weight: 0
    rules: |
      -N {{ ban_chain }}
  notify: Persist rules

- name: Set ban chain to simply drop if host banning is disabled
  set_fact:
    log_and_ban_chain: LOG_IN_DROP
    ban_chain: DROP
  when: not iptables_ban_hosts

- name: Create default logging chain
  include_tasks: log_chain.yml
  loop:
    - name: log-and-ban-chain
      rule_name: log-and-ban-chain
      state: present
      chain_name: "{{ log_and_ban_chain }}"
      prefix: "INPUT:DROP:"
      action: "{{ ban_chain }}"
    - name: output-drop
      rule_name: logging-output-drop-chain
      state: present
      chain_name: "{{ log_chain_output_drop }}"
      prefix: "OUTPUT:DROP:"
      action: DROP
  loop_control:
    loop_var: log_rule

- name: Make ansible iptables state files inaccessible to everyone
  file:
    path: /etc/ansible-iptables
    state: directory
    recurse: yes
    mode: 0600
    owner: root
    group: root