---

- name: Install iptables
  package:
    name: iptables
    state: present

- name: Install package to persist iptables rules
  package:
    name: "{{ iptables_save_package }}"
    state: present

- name: Make iptables persistance service start at boot
  service:
    name: "{{ iptables_save_service }}"
    enabled: true

- name: Create default logging chain
  include_tasks: log_chain.yml
  loop:
    - name: input-drop
      rule_name: logging-input-drop-chain
      state: present
      chain_name: "{{ log_chain_input_drop }}"
      prefix: "INPUT:DROP:"
      action: DROP
    - name: output-drop
      rule_name: logging-output-drop-chain
      state: present
      chain_name: "{{ log_chain_output_drop }}"
      prefix: "OUTPUT:DROP:"
      action: DROP
  loop_control:
    loop_var: log_rule

- name: Make ansible iptables state files inaccessible to everyone
  file:
    path: /etc/ansible-iptables
    state: directory
    recurse: yes
    mode: 0600
    owner: root
    group: root