---

- name: Install iptables
  package:
    name: iptables
    state: present

- name: Install package to persist iptables rules
  package:
    name: "{{ iptables_save_package }}"
    state: present

- name: Make iptables persistance service start at boot
  service:
    name: "{{ iptables_save_service }}"
    enabled: true

- name: Firewall rule - create ban chain
  iptables_raw:
    name: create-ban-chain
    state: "{{ (iptables_ban_hosts | bool) | ternary('present', 'absent') }}"
    weight: 0
    rules: |
      -N {{ ban_chain }}
  notify: Persist rules

- name: Set ban chain to simply drop if host banning is disabled
  set_fact:
    ban_chain: DROP
  when: not iptables_ban_hosts

- name: Create default logging chain
  include_tasks: log_chain.yml
  loop:
    - name: output-drop
      rule_name: logging-output-drop-chain
      state: present
      chain_name: "{{ log_chain_output_drop }}"
      prefix: "OUTPUT:DROP:"
      action: DROP
  loop_control:
    loop_var: log_rule