---

- name: Firewall rule - create default logging chains
  iptables_raw:
    name: "{{ item.rule_name }}"
    weight: 0
    rules: |
      -N {{ item.chain_name }}
      -A {{ item.chain_name }} -m limit --limit {{ iptables_log_limit }} -j LOG --log-prefix {{ item.prefix }} --log-level {{ iptables_log_level }} --log-uid
      -A {{ item.chain_name }} -j {{ item.action }}
  loop:
    - rule_name: logging-input-drop-chain
      chain_name: "{{ log_chain_input_drop }}"
      prefix: "INPUT:DROP:"
      action: DROP
    - rule_name: logging-output-drop-chain
      chain_name: "{{ log_chain_output_drop }}"
      prefix: "OUTPUT:DROP:"
      action: DROP
    - rule_name: logging-input-accept-chain
      chain_name: "{{ log_chain_input_accept }}"
      prefix: "INPUT:ACCEPT:"
      action: ACCEPT
    - rule_name: logging-output-accept-chain
      chain_name: "{{ log_chain_output_accept }}"
      prefix: "OUTPUT:ACCEPT:"
      action: ACCEPT
  notify: Persist rules

- name: Firewall rule - create helper chains
  iptables_raw:
    name: helper-chains
    weight: 0
    rules: |
      -N {{ inbound_accept_chain }}
      -A {{ inbound_accept_chain }} -m state --state NEW -j {{ log_chain_input_accept }}
      -A {{ inbound_accept_chain }} -m state --state ESTABLISHED,RELATED -j ACCEPT
      -N {{ outbound_accept_chain }}
      -A {{ outbound_accept_chain }} -m state --state NEW -j {{ log_chain_output_accept }}
      -A {{ outbound_accept_chain }} -m state --state ESTABLISHED,RELATED -j ACCEPT
  notify: Persist rules