---

- name: Firewall rule - create default logging chains
  include_tasks: log_chain.yml
  loop:
    - name: input-drop
      rule_name: logging-input-drop-chain
      state: present
      chain_name: "{{ log_chain_input_drop }}"
      prefix: "INPUT:DROP:"
      action: DROP
    - name: output-drop
      rule_name: logging-output-drop-chain
      state: present
      chain_name: "{{ log_chain_output_drop }}"
      prefix: "OUTPUT:DROP:"
      action: DROP
    - name: input-accept
      rule_name: logging-input-accept-chain
      state: present
      chain_name: "{{ log_chain_input_accept }}"
      prefix: "INPUT:ACCEPT:"
      action: ACCEPT
    - name: output-accept
      rule_name: logging-output-accept-chain
      state: present
      chain_name: "{{ log_chain_output_accept }}"
      prefix: "OUTPUT:ACCEPT:"
      action: ACCEPT

- name: Firewall rule - create default log helper chains
  include_tasks: log_helper_chain.yml
  loop:
    - name: input-accept
      rule_name: input-accept-helper-chain
      state: present
      chain_name: "{{ inbound_accept_chain }}"
      action: "{{ log_chain_input_accept }}"
    - name: output-accept
      rule_name: output-accept-helper-chain
      state: present
      chain_name: "{{ outbound_accept_chain }}"
      action: "{{ log_chain_output_accept }}"