---

- name: Firewall rule - allow ssh inbound
  iptables_raw:
    name: allow-ssh-inbound
    weight: 30
    rules: |
      -A INPUT -p tcp --dport {{ iptables_ssh_inbound_port }} -m state --state NEW -j {{ log_chain_input_accept }}
      -A INPUT -p tcp --dport {{ iptables_ssh_inbound_port }} -m state --state ESTABLISHED -j ACCEPT
      -A OUTPUT -p tcp --sport {{ iptables_ssh_inbound_port }} -m state --state ESTABLISHED {{ ('-m owner --uid-owner '~iptables_ssh_users) if iptables_ssh_users else '' }} -j ACCEPT
  when: iptables_allow_ssh_inbound | bool
  notify: Persist rules

- name: Firewall rule - allow ssh outbound
  iptables_raw:
    name: allow-ssh-outbound
    weight: 30
    rules: |
      -A OUTPUT -p tcp --dport {{ item }} -m state --state NEW {{ ('-m owner --uid-owner '~iptables_ssh_users) if iptables_ssh_users else '' }} -j {{ log_chain_output_accept }}
      -A OUTPUT -p tcp --dport {{ item }} -m state --state ESTABLISHED {{ ('-m owner --uid-owner '~iptables_ssh_users) if iptables_ssh_users else '' }} -j ACCEPT
      -A INPUT -p tcp --sport {{ item }} -m state --state ESTABLISHED -j ACCEPT
  loop: "{{ iptables_ssh_outbound_ports }}"
  when: iptables_allow_ssh_outbound | bool
  notify: Persist rules