---

- name: Initialize list of user inbound allow rules
  set_fact:
    user_service_inbound_rules: >
      {{ user_service_inbound_rules|default([]) + [{
        'name': item.name,
        'state': item.state | default('present'),
        'weight': 25,
        'proto': item.proto,
        'allow_inbound': true,
        'inbound_port': item.port,
        'allow_outbound': false,
        'outbound_ports': [],
        'users': [],
        'allowed': item.allowed | default([]),
        'blocked': item.blocked | default([]),
        'root_chain': '',
      }] }}
  loop: "{{ iptables_allow_inbound }}"

- name: Initialize list of user outbound allow rules
  set_fact:
    user_service_outbound_rules: >
      {{ user_service_outbound_rules|default([]) + [{
        'name': item.name,
        'state': item.state | default('present'),
        'weight': 25,
        'proto': item.proto,
        'allow_inbound': false,
        'inbound_port': '',
        'allow_outbound': true,
        'outbound_ports': item.ports,
        'users': item.users | default([]),
        'allowed': item.allowed | default([]),
        'blocked': item.blocked | default([]),
        'root_chain': (item.proto + '-' + (item.ports | string) | replace(',', '_') | replace(':', '-')) | upper,
      }] }}
    user_service_outbound_chains: >
      {{ user_service_outbound_chains|default([]) + [{
        'chain': (item.proto + '-' + (item.ports | string) | replace(',', '_') | replace(':', '-')) | upper,
        'proto': item.proto,
        'ports': item.ports,
      }] }}
  loop: "{{ iptables_allow_outbound }}"

- name: Create user inbound allow rules
  include_tasks: service_rules.yml
  loop: "{{ user_service_inbound_rules }}"

- name: Firewall rule - allow port(s) {{ item.ports }} over {{ item.proto }} outbound
  iptables_raw:
    name: "allow-{{ item.chain | lower }}-outbound"
    state: present
    weight: 24
    rules: |
      -N {{ item.chain }}
      -A OUTPUT -p {{ item.proto }} -m multiport --dports {{ item.ports }} -j {{ item.chain }}
      -A {{ item.chain }} -m state --state ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -p {{ item.proto }} -m multiport --sports {{ item.ports }} -m state --state ESTABLISHED,RELATED -j ACCEPT
  notify: Persist rules
  loop: "{{ user_service_outbound_chains | unique | list }}"

- name: Create user outbound allow rules
  include_tasks: service_rules.yml
  loop: "{{ user_service_outbound_rules }}"