---

- name: Initialize list of default allow rules
  set_fact:
    service_allow_rules:
      - name: ssh
        state: present
        weight: 30
        proto: tcp
        allow_inbound: "{{ iptables_allow_ssh_inbound | bool }}"
        inbound_port: "{{ iptables_ssh_inbound_port }}"
        allow_outbound: "{{ iptables_allow_ssh_outbound | bool }}"
        outbound_ports: "{{ iptables_ssh_outbound_ports }}"
        users: "{{ iptables_ssh_users }}"
      - name: ntp
        state: present
        weight: 35
        proto: udp
        allow_inbound: "{{ iptables_allow_ntp_inbound | bool }}"
        inbound_port: "{{ iptables_ntp_inbound_port }}"
        allow_outbound: "{{ iptables_allow_ntp_outbound | bool }}"
        outbound_ports: "{{ iptables_ntp_outbound_ports }}"
        users: "{{ iptables_ntp_users }}"
      - name: dns
        state: present
        weight: 40
        proto: udp
        allow_inbound: "{{ iptables_allow_dns_inbound | bool }}"
        inbound_port: "{{ iptables_dns_inbound_port }}"
        allow_outbound: "{{ iptables_allow_dns_outbound | bool }}"
        outbound_ports: "{{ iptables_dns_outbound_ports }}"
        users: "{{ iptables_dns_users }}"
      - name: http
        state: present
        weight: 45
        proto: tcp
        allow_inbound: "{{ iptables_allow_http_inbound | bool }}"
        inbound_port: "{{ iptables_http_inbound_port }}"
        allow_outbound: "{{ iptables_allow_http_outbound | bool }}"
        outbound_ports: "{{ iptables_http_outbound_ports }}"
        users: "{{ iptables_http_users }}"
      - name: https
        state: present
        weight: 50
        proto: tcp
        allow_inbound: "{{ iptables_allow_https_inbound | bool }}"
        inbound_port: "{{ iptables_https_inbound_port }}"
        allow_outbound: "{{ iptables_allow_https_outbound | bool }}"
        outbound_ports: "{{ iptables_https_outbound_ports }}"
        users: "{{ iptables_https_users }}"

- name: Create default allow rules
  include_tasks: service_rules.yml
  loop: "{{ service_allow_rules }}"