---

- name: Create global allow and block logging chains
  include_tasks: log_chain.yml
  loop:
    - name: global-allow-inbound-drop-chain
      rule_name: logging-global-allow-inbound-drop-chain
      state: "{{ (iptables_global_allow | length > 0) | ternary('present', 'absent') }}"
      chain_name: "{{ global_allow_inbound_log_chain }}"
      prefix: "GLOBAL_ALLOW:INPUT:DROP:"
      action: DROP
    - name: global-allow-outbound-drop-chain
      rule_name: logging-global-allow-outbound-drop-chain
      state: "{{ (iptables_global_allow | length > 0) | ternary('present', 'absent') }}"
      chain_name: "{{ global_allow_outbound_log_chain }}"
      prefix: "GLOBAL_ALLOW:OUTPUT:DROP:"
      action: DROP
    - name: global-block-inbound-drop-chain
      rule_name: logging-global-block-inbound-drop-chain
      state: "{{ (iptables_global_block | length > 0) | ternary('present', 'absent') }}"
      chain_name: "{{ global_block_inbound_log_chain }}"
      prefix: "GLOBAL_BLOCK:INPUT:DROP:"
      action: DROP
    - name: global-block-outbound-drop-chain
      rule_name: logging-global-block-outbound-drop-chain
      state: "{{ (iptables_global_block | length > 0) | ternary('present', 'absent') }}"
      chain_name: "{{ global_block_outbound_log_chain }}"
      prefix: "GLOBAL_BLOCK:OUTPUT:DROP:"
      action: DROP
  loop_control:
    loop_var: log_rule

- name: Create global allow or block lists
  include_tasks: create_lists.yml
  loop:
    - name: global
      match_blocked: true
      filter_inbound: true
      filter_outbound: true
      weight: 15
      allowed: "{{ iptables_global_allow }}"
      blocked: "{{ iptables_global_block }}"
      inbound_chain: INPUT
      outbound_chain: OUTPUT
      allowed_inbound_target: "{{ global_allow_inbound_log_chain }}"
      allowed_outbound_target: "{{ global_allow_outbound_log_chain }}"
      blocked_inbound_target: "{{ global_block_inbound_log_chain }}"
      blocked_outbound_target: "{{ global_block_outbound_log_chain }}"
  loop_control:
    loop_var: list