---

- name: Firewall rule - allow ping inbound and block ping of death
  iptables_raw:
    name: allow_ping_inbound
    weight: 60
    rules: |
      -N {{ ping_chain }}
      -A {{ ping_chain }} -p icmp --icmp-type echo-request -m hashlimit --hashlimit 1/s --hashlimit-burst 3 --hashlimit-htable-expire 300000 --hashlimit-mode srcip --hashlimit-name {{ iptables_death_ping_hashtable }} -j {{ log_chain_input_accept }}
      -A {{ ping_chain }} -j {{ log_chain_input_drop }}
      -A INPUT -p icmp --icmp-type echo-request -m state --state NEW,ESTABLISHED,RELATED -j {{ ping_chain }}
      -A OUTPUT -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -j ACCEPT
  when: iptables_allow_ping_inbound | bool
  notify: Persist rules

- name: Firewall rule - allow ping outbound
  iptables_raw:
    name: allow_ping_outbound
    weight: 60
    rules: |
      -A OUTPUT -p icmp --icmp-type echo-request -m state --state NEW,ESTABLISHED,RELATED {{ ('-m owner --uid-owner '~iptables_ping_user) if iptables_ping_user else '' }} -j {{ log_chain_output_accept }}
      -A INPUT -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -j ACCEPT
  when: iptables_allow_ping_outbound | bool
  notify: Persist rules