---

- name: Firewall rule - user inbound allow rules
  iptables_raw:
    name: user_allow_inbound
    weight: 23
    rules: |
      -A INPUT -p {{ item.proto }} --dport {{ item.port }} -m state --state NEW -j {{ log_chain_input_accept }}
      -A INPUT -p {{ item.proto }} --dport {{ item.port }} -m state --state ESTABLISHED -j ACCEPT
      -A OUTPUT -p {{ item.proto }} --sport {{ item.port }} -m state --state ESTABLISHED -j ACCEPT
  loop: "{{ iptables_allow_inbound }}"

- name: Firewall rule - user outbound allow rules
  iptables_raw:
    name: user_allow_outbound
    weight: 26
    rules: |
      -A OUTPUT -p {{ item.proto }} --dport {{ item.port }} -m state --state NEW -j {{ log_chain_input_accept }}
      -A OUTPUT -p {{ item.proto }} --dport {{ item.port }} -m state --state ESTABLISHED -j ACCEPT
      -A INPUT -p {{ item.proto }} --sport {{ item.port }} -m state --state ESTABLISHED -j ACCEPT
  loop: "{{ iptables_allow_outbound }}"

# TODO: allow setting users/groups
