---

- name: Firewall rule - allow package updating
  iptables_raw:
    name: allow-updates
    weight: 50
    rules: |
      -A OUTPUT -p udp --dport {{ default_dns_port }} {{ ('-m owner --uid-owner '~iptables_dns_user) if iptables_dns_user else '' }} -j {{ outbound_allow_chain }}
      -A INPUT -p udp --sport {{ default_dns_port }} -m state --state ESTABLISHED,RELATED -j ACCEPT
      -A OUTPUT -p tcp --dport {{ default_http_port }} {{ ('-m owner --uid-owner '~iptables_http_user) if iptables_http_user else '' }} -j {{ outbound_allow_chain }}
      -A INPUT -p tcp --sport {{ default_http_port }} -m state --state ESTABLISHED,RELATED -j ACCEPT
      -A OUTPUT -p tcp --dport {{ default_https_port }} {{ ('-m owner --uid-owner '~iptables_https_user) if iptables_https_user else '' }} -j {{ outbound_allow_chain }}
      -A INPUT -p tcp --sport {{ default_https_port }} -m state --state ESTABLISHED,RELATED -j ACCEPT
  when: iptables_allow_updates | bool
  notify: Persist rules

- name: Firewall rule - allow dns inbound
  iptables_raw:
    name: allow-dns-inbound
    weight: 50
    rules: |
      -A INPUT -p udp --dport {{ iptables_dns_inbound_port }} -j {{ inbound_allow_chain }}
      -A OUTPUT -p udp --sport {{ iptables_dns_inbound_port }} -m state --state ESTABLISHED,RELATED {{ ('-m owner --uid-owner '~iptables_dns_user) if iptables_dns_user else '' }} -j ACCEPT
  when: iptables_allow_dns_inbound | bool
  notify: Persist rules

- name: Firewall rule - allow http inbound
  iptables_raw:
    name: allow-http-inbound
    weight: 50
    rules: |
      -A INPUT -p tcp --dport {{ iptables_http_inbound_port }} -j {{ inbound_allow_chain }}
      -A OUTPUT -p tcp --sport {{ iptables_http_inbound_port }} -m state --state ESTABLISHED,RELATED {{ ('-m owner --uid-owner '~iptables_http_user) if iptables_http_user else '' }} -j ACCEPT
  when: iptables_allow_http_inbound | bool
  notify: Persist rules

- name: Firewall rule - allow https inbound
  iptables_raw:
    name: allow-https-inbound
    weight: 50
    rules: |
      -A INPUT -p tcp --dport {{ iptables_https_inbound_port }} -j {{ inbound_allow_chain }}
      -A OUTPUT -p tcp --sport {{ iptables_https_inbound_port }} -m state --state ESTABLISHED,RELATED {{ ('-m owner --uid-owner '~iptables_https_user) if iptables_https_user else '' }} -j ACCEPT
  when: iptables_allow_https_inbound | bool
  notify: Persist rules