---

- name: "Set bogon IPs"
  set_fact:
    bogon_ips: "{{ query('url', lookup('vars', 'bogon_list_url')) }}"
  when: iptables_block_bogons | bool

- name: "Unset bogon IPs"
  set_fact:
    bogon_ips: []
  when: not iptables_block_bogons

- name: Create bogon logging chains
  include_tasks: log_chain.yml
  loop:
    - name: bogons-inbound-drop-chain
      rule_name: logging-bogons-inbound-drop-chain
      state: "{{ (iptables_block_bogons | bool) | ternary('present', 'absent') }}"
      chain_name: "{{ bogons_inbound_log_chain }}"
      prefix: "BOGON:INPUT:DROP:"
      action: DROP
    - name: bogons-outbound-drop-chain
      rule_name: logging-bogons-outbound-drop-chain
      state: "{{ (iptables_block_bogons | bool) | ternary('present', 'absent') }}"
      chain_name: "{{ bogons_outbound_log_chain }}"
      prefix: "BOGON:OUTPUT:DROP:"
      action: DROP
  loop_control:
    loop_var: log_rule

- name: Block all traffic involving bogons
  include_tasks: create_lists.yml
  loop:
    - name: bogons
      weight: 17
      allowed: []
      blocked: "{{ bogon_ips }}"
      inbound_chain: INPUT
      outbound_chain: OUTPUT
      allowed_inbound_target: ""
      allowed_outbound_target: ""
      blocked_inbound_target: "{{ bogons_inbound_log_chain }}"
      blocked_outbound_target: "{{ bogons_outbound_log_chain }}"
  loop_control:
    loop_var: list