---

- name: Create ipset for banned hosts
  command: "ipset create {{ ipset_banned }} hash:ip family inet timeout {{ iptables_ban_duration }}"
  register: ipset_out
  changed_when: "'set with the same name already exists' not in ipset_out.stderr"
  failed_when: "ipset_out.rc != 0 and 'set with the same name already exists' not in ipset_out.stderr"

- name: Firewall rule - ban hosts that do not match rules
  iptables_raw:
    name: ban_chain
    weight: 6
    rules: |
      -N {{ ban_chain }}
      -A {{ ban_chain }} -m hashlimit --hashlimit-above {{ iptables_ban_interval }} --hashlimit-burst {{ iptables_ban_burst }} --hashlimit-htable-expire {{ iptables_ban_expire }} --hashlimit-mode srcip --hashlimit-name {{ iptables_suspicious_hashtable }} -j SET --add-set {{ ipset_banned }} src
      -A {{ ban_chain }} -j {{ log_chain_input_drop }}
  notify: Persist rules

- name: Firewall rule - drop banned traffic
  iptables_raw:
    name: drop_banned
    weight: 15
    rules: |
      -A INPUT -m set --set {{ ipset_banned }} src -j {{ log_chain_input_drop }}
  notify: Persist rules