---

- name: Initialize list of user inbound allow rules
  set_fact:
    user_service_inbound_rules: >
      {{ user_service_inbound_rules|default([]) + [{
        'name': item.name,
        'weight': 25,
        'proto': item.proto,
        'allow_inbound': true,
        'inbound_port': item.port,
        'allow_outbound': false,
        'outbound_ports': [],
        'users': item.users
      }] }}
  loop: "{{ iptables_allow_inbound }}"

- name: Initialize list of user outbound allow rules
  set_fact:
    iptables_allow_outbound: >
      {{ iptables_allow_outbound|default([]) + [{
        'name': item.name,
        'weight': 25,
        'proto': item.proto,
        'allow_inbound': false,
        'inbound_port': '',
        'allow_outbound': true,
        'outbound_ports': [item.port],
        'users': item.users
      }] }}
  loop: "{{ iptables_allow_outbound }}"

- name: Create user inbound allow rules
  include_tasks: service_rules.yml
  loop: "{{ user_service_inbound_rules }}"
  when: user_service_inbound_rules | length > 0

- name: Create user outbound allow rules
  include_tasks: service_rules.yml
  loop: "{{ iptables_allow_outbound }}"
  when: iptables_allow_outbound | length > 0