---

- name: Create ipset for banned hosts
  command: ipset create {{ ipset_banned }} hash:ip family inet timeout {{ iptables_ban_duration }}
  when: iptables_ban_hosts | bool

- name: Firewall rule - ban hosts that do not match rules
  iptables_raw:
    name: ban_chain
    weight: 6
    rules: |
      -N {{ ban_chain }}
      -A {{ ban_chain }} -m hashlimit --hashlimit-above {{ iptables_ban_interval }} --hashlimit-burst {{ iptables_ban_burst }} --hashlimit-htable-expire {{ iptables_ban_expire }} --hashlimit-mode srcip --hashlimit-name {{ iptables_suspicious_hashtable }} -j SET --add-set {{ ipset_banned }} src
      -A {{ ban_chain }} -j {{ log_chain_input_drop }}
  when: iptables_ban_hosts | bool

- name: Firewall rule - drop banned traffic
  iptables_raw:
    name: drop_banned
    weight: 15
    rules: |
      -A INPUT -m set --set {{ ipset_banned }} src -j {{ log_chain_input_drop }}
  when: iptables_ban_hosts | bool

- name: Firewall rule - block portscans and attacks
  iptables_raw:
    name: prevent-attacks
    weight: 20
    rules: |
      -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ACK,URG URG -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ALL ALL -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ALL NONE -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ALL FIN,PSH,URG -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j {{ ban_chain }}
      -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j {{ ban_chain }}
      -A INPUT -f -j {{ ban_chain }}
      -A INPUT -p tcp ! --syn -m state --state NEW -j {{ ban_chain }}
