---

- name: Firewall rule - create {{ item.name }} helper chain
  iptables_raw:
    name: "{{ item.rule_name }}"
    state: "{{ item.state }}"
    weight: 0
    rules: |
      -N {{ item.chain_name }}
      -A {{ item.chain_name }} -m state --state NEW -j {{ item.action }}
      -A {{ item.chain_name }} -m state --state ESTABLISHED,RELATED -j ACCEPT
  notify: Persist rules