---

- name: Firewall rule - create {{ log_rule.name }} logging chain
  iptables_raw:
    name: "{{ log_rule.rule_name }}"
    state: "{{ log_rule.state }}"
    weight: 0
    rules: |
      -N {{ log_rule.chain_name }}
      -A {{ log_rule.chain_name }} -m limit --limit {{ iptables_log_limit }} -j LOG --log-prefix {{ log_rule.prefix }} --log-level {{ iptables_log_level }} --log-uid
      -A {{ log_rule.chain_name }} -j {{ log_rule.action }}
  notify: Persist rules