---

- name: "Set {{ item.name }} chain names"
  set_fact:
    current_log_chain: "{{ item.name | upper }}_LOG"
    current_accept_chain: "{{ item.name | upper }}_ACCEPT"

- name: "Firewall rule - create {{ item.name }} chains"
  iptables_raw:
    name: "create-{{ item.name }}-chains"
    weight: "{{ item.weight }}"
    rules: |
      -N {{ current_log_chain }}
      -N {{ current_accept_chain }}
  when: item.users | length > 0
  notify: Persist rules

- name: "Set {{ item.name }} chains if user filtering is disabled"
  set_fact:
    current_log_chain: "{{ outbound_accept_chain }}"
    current_accept_chain: ACCEPT
  when: item.users | length == 0

- name: "Firewall rule - filter outbound {{ item.name }} traffic by user"
  iptables_raw:
    name: "filter-{{ item.name }}-outbound-{{ user }}"
    weight: "{{ item.weight }}"
    rules: |
      -A {{ current_log_chain }} -m owner --uid-owner {{ user }} -j {{ outbound_accept_chain }}
      -A {{ current_accept_chain }} -m owner --uid-owner {{ user }} -j ACCEPT
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user
  notify: Persist rules

- name: Firewall rule - allow TCP to close connections
  iptables_raw:
    name: "allow-{{ item.name }}-closed"
    weight: "{{ item.weight }}"
    rules: |
      -A {{ current_log_chain }} -m owner ! --socket-exists -j ACCEPT
      -A {{ current_accept_chain }} -m owner ! --socket-exists -j ACCEPT
  when: (item.users | length > 0) and (item.proto | lower == 'tcp')
  notify: Persist rules

- name: "Firewall rule - allow {{ item.name }} inbound"
  iptables_raw:
    name: "allow-{{ item.name }}-inbound"
    weight: "{{ item.weight }}"
    rules: |
      -A INPUT -p {{ item.proto }} --dport {{ item.inbound_port }} -j {{ inbound_accept_chain }}
      -A OUTPUT -p {{ item.proto }} --sport {{ item.inbound_port }} -m state --state ESTABLISHED,RELATED -j {{ current_accept_chain }}
  when: item.allow_inbound | bool
  notify: Persist rules

- name: "Firewall rule - allow {{ item.name }} outbound"
  iptables_raw:
    name: "allow-{{ item.name }}-outbound"
    weight: "{{ item.weight }}"
    rules: |
      -A OUTPUT -p {{ item.proto }} -m multiport --dports {{ item.outbound_ports }} -j {{ current_log_chain }}
      -A INPUT -p {{ item.proto }} -m multiport --sports {{ item.outbound_ports }} -m state --state ESTABLISHED,RELATED -j ACCEPT
  when: item.allow_outbound | bool
  notify: Persist rules